spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.221.121:3306/mqtt?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimeZone=GMT%2B8
    username: root
    password: GZJ72610-.-

# 整合mybatis
mybatis:
  type-aliases-package: com.iot.pojo
  mapper-locations: classpath:mapper/*.xml

